name: haydi_express_restaurant
description: "Haydi Express Restaurant App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #State Management
  mobx: ^2.2.0
  mobx_codegen: ^2.4.0
  flutter_mobx: ^2.1.0


  #Generating
  build_runner: ^2.4.6
  uuid: ^4.3.3
  intl: ^0.19.0

  #UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  easy_loading_button: ^0.3.2
  window_manager: ^0.3.8
  passwordfield:
  calendar_date_picker2: ^0.5.3
  toastification: ^1.2.1

  #File
  shared_preferences: ^2.2.1
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  file_selector: ^1.0.3

  #Network
  dio:
  socket_io_client: ^3.0.0-beta.2
  http_parser: ^4.0.2
  
  
  
  
  #web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/meta/


