name: haydi_express_restaurant
description: "Haydi Express Restaurant App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #Devtools
  haydi_ekspres_dev_tools:
    path: ../haydi_ekspres_dev_tools

  #File
  sqlite3:
  #sqlite3_flutter_libs:
  path_provider: ^2.1.1
  file_selector: ^1.0.3

  #UI
  window_manager: ^0.3.9
  
  
  
  
  #web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

assets:
  - packages/haydi_ekspres_dev_tools/lib/assets/icons/
  - packages/haydi_ekspres_dev_tools/lib/assets/images/
  - packages/haydi_ekspres_dev_tools/lib/assets/meta/




